services:
  redis:
    image: redis:7.0
    container_name: redis_worker
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - broker_connection_retry_on_startup=True
    volumes:
      - ./worker_tasks.py:/app/worker_tasks.py
      - ./celery_config.py:/app/celery_config.py
    command: celery -A worker_tasks worker --loglevel=info

  model_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: model_server
    depends_on:
      - redis
    environment:
      - TRANSFORMERS_CACHE=/models
    volumes:
      - ./models:/models
    ports:
      - "5000:5000"

volumes:
  redis_data:
